require 'user.options'
require 'user.keymaps'
require 'user.plugins'
require 'user.telescope'
require 'user.colorscheme'
require 'user.lualine'
require 'user.bufferline'
require 'user.nvim-tree'
require 'user.toggleterm'
require 'user.impatient'
-- require 'user.autocompletion'
-- require 'user.lsp'
-- require 'user.treesitter'
-- require 'user.autopairs'
-- require 'user.comment'
